// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("Admin")]
public partial class Admin
{
    [Key]
    public int UserId { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Admin")]
    public virtual User User { get; set; }
}