// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("Customer")]
public partial class Customer
{
    [Key]
    public int UserId { get; set; }

    [InverseProperty("Customer")]
    public virtual ICollection<Rate> Rates { get; set; } = new List<Rate>();

    [ForeignKey("UserId")]
    [InverseProperty("Customer")]
    public virtual User User { get; set; }
}