// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("NotificationMessage")]
public partial class NotificationMessage
{
    [Key]
    public int MsgId { get; set; }

    public int UserId { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    public string MsgContent { get; set; }

    public DateTime SendingDate { get; set; }

    public bool Seen { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("NotificationMessages")]
    public virtual User User { get; set; }
}