// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("Offer")]
[Index(nameof(Title), IsUnique = true)] // Adding Index to Title for searching and uniqueness
public partial class Offer
{
    [Key]
    public int OfferId { get; set; }

    [StringLength(50)]
    public string Title { get; set; }

    [StringLength(200)]
    public string Image { get; set; }

    public string Description { get; set; }

    public DateOnly OfferDate { get; set; }

    public int Duration { get; set; }

    public decimal? PackageDiscount { get; set; } = 0;


    [InverseProperty("Offer")]
    public virtual ICollection<ProductOffer> ProductOffers { get; set; } = new List<ProductOffer>();
    public virtual ICollection<Order> Orders { get; set; } = new List<Order>();
}