// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using ECommereceApi.Enums;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("Order")]
public partial class Order
{

    [Key]
    public Guid OrderId { get; set; }

    [StringLength(50)]
    public string Governerate { get; set; }

    [StringLength(50)]
    public string City { get; set; }

    [StringLength(50)]
    public string Street { get; set; }

    [StringLength(50)]
    public string PostalCode { get; set; }

    public DateOnly? ArrivalDate { get; set; }

    public int UserId { get; set; }

    public OrderStatus Status { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("Orders")]
    public virtual User User { get; set; }

    [InverseProperty("Order")]
    public virtual ICollection<ProductOrder> ProductOrders { get; set; }


    // Computed properties
    [NotMapped]
	public DateOnly? ResponseDate { get; set; }

	[NotMapped]
	public double? TotalPrice { get; set; }

	[NotMapped]
	public int? TotalAmount { get; set; }
}