// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[PrimaryKey("ProductId", "SubId")]
[Table("ProductSubCategory")]
[Index("SubId", Name = "IX_ProductSubCategory_SubId")]
public partial class ProductSubCategory
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int SubId { get; set; }

    [Required]
    [StringLength(50)]
    public string SubCategoryValue { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductSubCategories")]
    public virtual Product Product { get; set; }

    [ForeignKey("SubId")]
    [InverseProperty("ProductSubCategories")]
    public virtual SubCategory Sub { get; set; }
}