// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[PrimaryKey("ProductId", "OfferId")]
[Table("ProductOffer")]
public partial class ProductOffer
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int OfferId { get; set; }

    public int ProductAmount { get; set; }

    public double? Discount { get; set; }

    [ForeignKey("OfferId")]
    [InverseProperty("ProductOffers")]
    public virtual Offer Offer { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductOffers")]
    public virtual Product Product { get; set; }
}