// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[PrimaryKey("ProductId", "UserId")]
[Table("ProductCart")]
public partial class ProductCart
{
    [Key]
    public int ProductId { get; set; }

    [Key]
    public int UserId { get; set; }

    public int ProductAmount { get; set; }

    [ForeignKey("ProductId")]
    [InverseProperty("ProductCarts")]
    public virtual Product Product { get; set; }

    [ForeignKey("UserId")]
    [InverseProperty("ProductCarts")]
    public virtual User User { get; set; }

    // Computed properties

    [NotMapped]
    public double? TotalPrice { get; set; }

	[NotMapped]
	public int? TotalAmount { get; set; }

    [NotMapped]
	public double? ProductTotalPrice { get; set; }
}