// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("SubCategory")]
public partial class SubCategory
{
    [Key]
    public int SubId { get; set; }

    [StringLength(50)]
    public string Name { get; set; }

    [InverseProperty("Sub")]
    public virtual ICollection<ProductSubCategory> ProductSubCategories { get; set; } = new List<ProductSubCategory>();

    [ForeignKey("SubId")]
    [InverseProperty("Subs")]
    public virtual ICollection<Category> Categories { get; set; } = new List<Category>();
}