// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace ECommereceApi.Models;

[Table("Web_Info")]
public partial class WebInfo
{
    [Key]
    public int WebInfoId { get; set; } 

    [StringLength(50)]
    public string WebPhone { get; set; }

    [StringLength(50)]
    public string WebName { get; set; }

    [StringLength(200)]
    public string WebLogoImageUrl { get; set; }

    [StringLength(50)]
    public string InstagramAccount { get; set; }

    [StringLength(50)]
    public string FacebookAccount { get; set; }
}